Update Editor Config
PolyhedralDev/Terra pull request #218
Opened 2021-06-16 02:25 UTC by solonovamax

# Pull Request

## Brief description.

Update the editor config to better reflect current java standards

### What Issues Does This Fix?

## Licensing

- [x] I am the original author of this code, and I am willing to release it under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).
- [ ] I am not the original author of this code, but it is in public domain or released
  under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) or a compatible license.
    

## Goal of the PR

- [x] Make code style better reflect modern java standards

## Affects of the PR

#### Types of changes

- [ ] Bug Fix 
- [ ] Build system 
- [ ] Documentation 
- [ ] New Feature 
- [ ] Performance 
- [ ] Refactoring 
- [ ] Repository 
- [ ] Revert 
- [x] Style 
- [ ] Tests 
- [ ] Translation 

#### Compatiblity

- [ ] Breaking change 
- [x] Non-Breaking change.
    

#### Contribution Guidelines.

- [x] I have read the [`CONTRIBUTING.md`](https://github.com/PolyhedralDev/Terra/blob/master/CONTRIBUTING.md) document in the root of the
  git repository.
- [x] My code follows the code style for this
  project. 

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Testing

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-06-21 23:39 UTC, dfsek commented on common/src/main/java/com/dfsek/terra/addon/AddonClassLoader.java
> +        final JarFile jarFile = new JarFile(file);
Turn off whatever is doing this (the `final` spam).

2021-06-21 23:39 UTC, dfsek commented on common/src/main/java/com/dfsek/terra/addon/AddonClassLoader.java
> +            } catch(final ClassNotFoundException e) {
And this (`final` spam on `catch`)

2021-06-21 23:40 UTC, dfsek requested changes

2021-06-21 23:40 UTC, dfsek commented on common/src/main/java/com/dfsek/terra/addon/AddonPool.java
> +    public void add(final PreLoadAddon addon) throws AddonLoadException {
And this. (`final` spam on method parameters)

2021-06-22 00:57 UTC, dfsek commented on common/src/main/java/com/dfsek/terra/api/event/TerraEventManager.java
> +                                                                                      try {
why on earth is this so far over    
it was fine the way it was

2021-06-22 01:06 UTC, dfsek commented on common/src/main/java/com/dfsek/terra/api/math/noise/samplers/ImageSampler.java
> +        },
TBH i much prefer these on the same line

2021-08-30 14:51 UTC, solonovamax commented
Going to close this and reopen it with a cleaner history

2021-08-30 14:51 UTC, closed without merging