Mitigate issues with tree generation in paper
PolyhedralDev/Terra pull request #260
Opened 2021-08-29 05:50 UTC by Cubxity

# Pull Request

## Brief description.

This mitigates https://github.com/PaperMC/Paper/issues/6028 by try-catching tree generation. 

### What Issues Does This Fix?

## Licensing

- [x] I am the original author of this code, and I am willing to release it under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).
- [ ] I am not the original author of this code, but it is in public domain or released
  under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) or a compatible license.

## Goal of the PR

- [x] Fixes crash caused by Paper tree generation bug

## Affects of the PR

This prevents the tree generation bug from crashing the server. 

#### Types of changes

- [x] Bug Fix 
- [ ] Build system 
- [ ] Documentation 
- [ ] New Feature 
- [ ] Performance 
- [ ] Refactoring 
- [ ] Repository 
- [ ] Revert 
- [ ] Style 
- [ ] Tests 
- [ ] Translation 

#### Compatiblity

- [ ] Breaking change 
- [x] Non-Breaking change.

#### Contribution Guidelines.

- [x] I have read the [`CONTRIBUTING.md`](https://github.com/PolyhedralDev/Terra/blob/master/CONTRIBUTING.md) document in the root of the
  git repository.
- [x] My code follows the code style for this
  project. 

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Testing

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-08-30 00:22 UTC, dfsek requested changes

2021-08-30 00:22 UTC, dfsek commented on platforms/bukkit/src/main/java/com/dfsek/terra/bukkit/world/BukkitTree.java
> +        } catch(Exception ignored) {
Catch the specific exception.

2021-08-30 14:46 UTC, solonovamax approved these changes
Seems pretty fine to me

2021-08-30 14:46 UTC, solonovamax commented on platforms/bukkit/src/main/java/com/dfsek/terra/bukkit/world/BukkitTree.java
> +        } catch(IndexOutOfBoundsException ignored) {
Perhaps we should log something referencing PaperMC/Paper#6028?

2021-09-06 19:44 UTC, dfsek approved these changes

2021-09-06 19:44 UTC, merged