feat: Minestom platform
PolyhedralDev/Terra pull request #485
Opened 2024-12-29 19:42 UTC by Bloeckchengrafik

# Pull Request

## Description

This PR implements the terra platform for minestom. You can read more about how this port works on my [blog](https://bloeckchengrafik.de/blog/terra-minestom/) or by looking at the code :)

I just want to get this out here even if it is not complete to get some early feedback on my code. So if you think I should do something different, please let me know! 

Closes #113

### Changelog

- [ ] Add support for Minestom

## Checklist

#### Mandatory checks

- [x] The base branch of this PR is an unreleased version branch (that has a `ver/` prefix)
  or is a branch that is intended to be merged into a version branch.
  
- [x] There are no already existing PRs that provide the same changes.
  
- [x] The PR is within the scope of Terra (i.e. is something a configurable terrain generator should be doing).
- [ x Changes follow the code style for this project.
  
- [x] I have read the [`CONTRIBUTING.md`](https://github.com/PolyhedralDev/Terra/blob/master/CONTRIBUTING.md)
  document in the root of the git repository.

#### Types of changes

- [ ] Bug Fix 
- [ ] Build system 
- [ ] Documentation 
- [x] New Feature 
- [ ] Performance 
- [ ] Refactoring 
- [ ] Repository 
- [ ] Revert 
- [ ] Style 
- [ ] Tests 
- [ ] Translation 

#### Compatibility

- [ ] Introduces a breaking change
  
- [x] Introduces new functionality in a backwards compatible way.
- [ ] Introduces bug fixes

#### Documentation

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

I'll add docs to the TerraDocs-Repo when this is done

#### Testing

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
  

#### Licensing

- [x] I am the original author of this code, and I am willing to
  release it under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).
- [ ] I am not the original author of this code, but it is in public domain or
  released under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) or a compatible license.

2025-01-02 22:47 UTC, Bloeckchengrafik commented
I'm done here for now! Please leave a code review and try it out!
Using `./gradlew :platforms:minestom:run`, you can start a test server and with `/regenerate` you can
regenerate the world.

If you have any questions or notes about my implementation, please let me know here or in discord!

2025-01-03 20:48 UTC, solonovamax requested changes

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/TerraMinestomExample.java
> +public class TerraMinestomExample {
Why is this file committed to the `main` source set?

2025-01-03 20:48 UTC, solonovamax commented on common/api/src/main/java/com/dfsek/terra/api/block/BlockType.java
> + * your platform implementation for surface decorations to show up
should probably be a separate PR

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/build.gradle.kts
> +addonDir(project.file("./run/terra/addons"), tasks.named("run").get())
afaik somewhere you need to depend on the `installAddons` task.

see: https://github.com/PolyhedralDev/Terra/blob/0a952cff4c3eea8bc0a49205643e0c225d12304c/platforms/fabric/build.gradle.kts#L47-L55

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/build.gradle.kts
> +    entryCompression = ZipEntryCompression.STORED
Why are you setting the entry compression to `STORED`?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/MinestomPlatform.java
> +    }
Why is `reload` not supported?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/TerraMinestomExample.java
> +//            .seed(0)
remove commented out code

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/api/filter/EvenChunkFilter.java
> +public class EvenChunkFilter implements ChunkFilter {
Why do we have this?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/api/filter/NoFeaturesFilter.java
> +public class NoFeaturesFilter implements ChunkFilter {
Why do we have this?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/api/filter/NoTerrainFilter.java
> +public class NoTerrainFilter implements ChunkFilter {
Why do we have this?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/api/filter/XFilter.java
> +public class XFilter implements ChunkFilter {
Why do we have this?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/api/filter/ZFilter.java
> +public class ZFilter implements ChunkFilter {
Why do we have this?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/api/filter/SpecificChunkFilter.java
> +public class SpecificChunkFilter implements ChunkFilter {
Why do we have this?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/block/MinestomBlockState.java
> +    }
Is this constructor ever used?
If not, then it should be removed.

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/chunk/GeneratedChunkCache.java
> +public class GeneratedChunkCache {
Why is this needed?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/entity/DeferredMinestomEntity.java
> +public class DeferredMinestomEntity implements Entity {
Why is this needed?

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/world/MinestomChunkGeneratorWrapper.java
> +public class MinestomChunkGeneratorWrapper implements Generator {
Why is this not implementing `GeneratorWrapper`?

eg. https://github.com/PolyhedralDev/Terra/blob/0a952cff4c3eea8bc0a49205643e0c225d12304c/platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/generator/BukkitChunkGeneratorWrapper.java#L40

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/MinestomPlatform.java
> +import java.io.File;
Weird formatting, please reformat.
Applies to all files.

2025-01-03 20:48 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/world/TerraMinestomWorldBuilder.java
> +public class TerraMinestomWorldBuilder {
Why do we have this?

2025-01-03 21:16 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/TerraMinestomExample.java
> +public class TerraMinestomExample {
Do you think it would be good to create a seperate module for the example? I think that might the best option

Currently I have it in there because it makes it easy to try out.

What do you think?

2025-01-03 21:17 UTC, Bloeckchengrafik commented on common/api/src/main/java/com/dfsek/terra/api/block/BlockType.java
> + * your platform implementation for surface decorations to show up
We can also just leave it out here. I'll remove it for now

2025-01-03 22:53 UTC, Bloeckchengrafik commented on platforms/minestom/build.gradle.kts
> +addonDir(project.file("./run/terra/addons"), tasks.named("run").get())
Should be fixed by the latest commit

2025-01-03 22:54 UTC, Bloeckchengrafik commented on platforms/minestom/build.gradle.kts
> +    entryCompression = ZipEntryCompression.STORED
Copied this from bukkit. Why is it there?

2025-01-03 23:09 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/MinestomPlatform.java
> +    }
An oversight on my part, should be fixed

2025-01-03 23:10 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/api/filter/EvenChunkFilter.java
> +public class EvenChunkFilter implements ChunkFilter {
Artifact from debugging, sorry

2025-01-03 23:12 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/block/MinestomBlockState.java
> +    }
Used by `MinestomWorldHandle#createBlockState`

2025-01-03 23:13 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/chunk/GeneratedChunkCache.java
> +public class GeneratedChunkCache {
Minestom does not implement separate stages between terrain and feature generation as of now. This is needed to store terrain for "ungenerated" chunks for feature generation, since we can't just load them via minestom

2025-01-03 23:17 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/entity/DeferredMinestomEntity.java
> +public class DeferredMinestomEntity implements Entity {
During World generation, no entities can be placed in minestom. This uses the async chunk loading api to create the entities after the world is loaded

2025-01-03 23:18 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/world/MinestomChunkGeneratorWrapper.java
> +public class MinestomChunkGeneratorWrapper implements Generator {
fixed

2025-01-03 23:21 UTC, Bloeckchengrafik commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/world/TerraMinestomWorldBuilder.java
> +public class TerraMinestomWorldBuilder {
The `TerraMinestomWorld` class has a lot of parameters. Since Minestom is not configured like bukkit, all worlds need to be created through the API. This makes it easier to create a world. See the provided example for more details

2025-01-05 01:59 UTC, solonovamax commented on platforms/minestom/src/main/java/com/dfsek/terra/minestom/TerraMinestomExample.java
> +public class TerraMinestomExample {
it should absolutely be a separate module.

2025-01-05 16:06 UTC, Bloeckchengrafik commented on platforms/minestom/build.gradle.kts
> +    entryCompression = ZipEntryCompression.STORED
removed it

2025-02-26 17:22 UTC, merged